@startuml
(*) --> "Переход на страницу Авторизации"

if "Есть аккаунт" then
    -->[да] "Вход"
else
    -->[нет] "Регистрация"
Endif
"Регистрация" --> "Ввод email и password (1)"


"Ввод email и password (1)" --> "Отправка данных (1)"
if "Валидация пройдена" then
    if "Email занят" then
        -->[да] "Регистрация"
    else
        -->[нет] "Пользователь создан"
    Endif
else
    -->[нет] "Регистрация" 
Endif

"Вход" --> if "Забыл пароль" then
            -->[да] "Восстановление"
        else
            -->[нет] "Ввод email и password (2)"
        Endif   

"Ввод email и password (2)" --> "Отправка данных (2)"
"Отправка данных (2)" --> if "Валидация пройдена" then
    if "Пользователь найден" then 
        -->[да] "Вход в аккаунт"
    else
        -->[нет] "Вход"
    Endif  
else
    -->[нет] "Вход"
Endif  

"Восстановление" --> "Ввод email"
if "Email найден" then 
    -->[да] "Отправка письма для восстановления пароля"
else
    -->[нет] "Восстановление"
Endif  

"Пользователь создан" --> (*)
"Вход в аккаунт" --> (*)

@enduml
 