@startuml
(*) --> "Переход на страницу Диск"
"Переход на страницу Диск" --> ===B1===
--> "Перетащить нужные файлы в dropzone"
--> ===B2=== 

===B1=== --> "Нажать на кнопку 'Загрузить файл'"
"Нажать на кнопку 'Загрузить файл'" --> "Выбрать нужный файл на комп."
"Выбрать нужный файл на комп." --> "Загрузить"
--> ===B2===



if "файл существует" then 
-->[да] "Переход на страницу Диск"
else 
-->[нет] "Далее"

if "достаточно места на диске" then 
--> [да] "Успешная загрузка на сервер"
else 
-->[нет] "Переход на страницу Диск"

"Успешная загрузка на сервер" --> (*)
 
@enduml

