@startuml
(*) --> "Переход на страницу Диск"
if "Посмотреть файл" then
    -->[Да] "Выбрать файл" 
    --> ===B1===
    --> "нажать правой кнопки мыши"
    --> "нажать на кнопку 'открыть'"
    --> ===B2=== 
    ===B1=== --> "нажать левой кнопки мыши 2 рааз"
    --> ===B2=== 
    --> (*)
else
    -->[нет](*)
@enduml