@startuml

:Пользователь: --> (аутентификация)

аутентификация --> (регистрация)
аутентификация --> (вход)
аутентификация --> (восстановление пароля)
регистрация --> (навигация)
вход --> (навигация)
(восстановление пароля) --> (вход)
навигация -> (профиль)
навигация --> (диск)

диск --> (загрузка файлов)#line.dashed
диск --> (просмотр файлов)#line.dashed
диск --> (изменение файлов)#line.dashed
диск --> (скачивание файлов)#line.dashed
диск --> (удаление файлов)#line.dashed

профиль -> (выход)#line.dashed;
профиль --> (удаление профиля)#line.dashed;
профиль --> (изменение профиля)#line.dashed;

:Друг: --> (просмотр файлов по ссылке)#line.dashed;
:Друг: --> (скачивание файлов по ссылке)#line.dashed;
:Друг: --> (аутентификация)#line.dashed;

@enduml